### ISSUE TITLE
control seat heating

### ISSUE THREAD

**Issue by mrniemand** [SAIC-iSmart-API/saic-python-mqtt-gateway#112] opened 2023-12-04 18:54 UTC
is it anyhow possible to switch on the seat heating? In the original app its possible (unfortunally not the stearing wheel heating)

**Comment by TripelJ** [comment] 2024-01-12 09:23
@mrniemand Which car do you have that allows control og the seat heating from the iSMART app ? 
I have a Marvel R and that is not possible in the new or old app for iOS.

**Comment by mrniemand** [comment] 2024-01-12 19:27
i have an MG4 trophy. It was allready in the old app

**Comment by nanomad** [comment] 2024-01-21 20:06
Closing as duplicate of #127

**Closed by nanomad** 2024-01-21 20:06 UTC
